In [2]:
import numpy as np

import sys
import os
sys.path.append(os.path.abspath('..'))

# useful factorization
from Factorizations.PLU_Decomposition import PLU_Decomposition

# useful solver for linear systems

### Exercise 1
Considering the following graph:
<div style="text-align: center;">
    <img src="Graphs_Images/Graph_1.png" width="200" style="border: 3px solid white; border-radius: 10px;">
</div>

It's possible to compute the score:
$$
x_k = \sum_{j\in L_k}\frac{x_j}{n_j} \quad \forall k\in \{1,2,3,4\}\quad (1) 
$$
Where $L_k$ is the set of the nodes with a direct arc coming into k, $n_j$ is the number of direct arc that starts from the node $j$ and $x_k$ is the score for the node $k$. 

The equation (1) can be expressed in it's matricial form:
$$
\mathbf{x}^T\mathbf{A} = \mathbf{x} \implies (\mathbf{A}^T-\mathbf{I_d})\mathbf{x} = \mathbf{0}
$$
Where $\mathbf{A}\in\mathbb{R}^{4\times4}$ is the **Weighted Adjacency Matrix** of the graph.
$$
A =
\begin{bmatrix}
0 & 0 & 1 & \frac{1}{2} \\
\frac{1}{3} & 0 & 0 & 0 \\
\frac{1}{3} & \frac{1}{2} & 0 & \frac{1}{2} \\
\frac{1}{3} & \frac{1}{2} & 0 & 0
\end{bmatrix} \quad (2)
$$

In [3]:

A1 = np.array([
    [0, 0, 1, 1/2],
    [1/3, 0, 0, 0],
    [1/3, 1/2, 0, 1/2], 
    [1/3, 1/2, 0, 0]
])

P,L,U, norm = PLU_Decomposition(A1)
print("L:\n", L)
print("U:\n", U)
print("P:\n", P)
print("Difference ||PA - LU|| =\n",norm)


L:
 [[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 1.]]
U:
 [[ 0.33333333  0.          0.          0.        ]
 [ 0.          0.5         0.          0.5       ]
 [ 0.          0.          1.          0.5       ]
 [ 0.          0.          0.         -0.5       ]]
P:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
Difference ||PA - LU|| =
 0.0
